# Cloudflare Pages 专用配置文件
# 这个文件会被 Pages 自动识别

name = "augment-license-server"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages 构建配置
pages_build_output_dir = "public"

# 环境变量
[vars]
ENVIRONMENT = "production"
LICENSE_IDENTITY = "AugmentCode"
EXPIRE_AFTER = "31536000000"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "augment-licenses"
database_id = "your-database-id-here"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production", LICENSE_IDENTITY = "AugmentCode", EXPIRE_AFTER = "31536000000" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "augment-licenses"
database_id = "your-database-id-here"

# 预览环境配置
[env.preview]
vars = { ENVIRONMENT = "preview", LICENSE_IDENTITY = "AugmentCode", EXPIRE_AFTER = "31536000000" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "augment-licenses"
database_id = "your-database-id-here"