# Cloudflare Workers 配置
name = "augment-license-server"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 配置
pages_build_output_dir = "public"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "augment-licenses"
database_id = "your-database-id-here"  # 需要替换为实际的数据库ID

# 环境变量
[vars]
ENVIRONMENT = "development"
LICENSE_IDENTITY = "AugmentCode"
EXPIRE_AFTER = "31536000000"  # 1年，单位毫秒

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }

# 开发环境配置  
[env.development]
vars = { ENVIRONMENT = "development" }

# 密钥配置（通过 wrangler secret 命令设置）
# wrangler secret put RSA_PRIVATE_KEY
# wrangler secret put RSA_PUBLIC_KEY
# wrangler secret put ADMIN_API_KEY